main:
	gcc -g -o rathee main.c prompt.c warp.c peek.c proclore.c past.c seek.c process.c input.c redirect.c activities.c fg.c bg.c ping.c

walli :
	wall gcc -g main.c prompt.c warp.c peek.c proclore.c past.c seek.c process.c input.c


	
